authors = ["Li Yifeng <mail@yifen9.li>"]
license = "MIT"
name = "SpringRank"
uuid = "be6e8a61-07d1-4c53-9ea3-a8f885d7be3a"
version = "0.1.0"

[compat]
julia = "1.12"
Graphs = "1.13"
IterativeSolvers = "0.9"
LinearAlgebra = "1.12"
SparseArrays = "1.12"
Statistics = "1.11"
Tables = "1.12"

[deps]
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
IterativeSolvers = "42fd0dbc-a981-5370-80f2-aaf504508153"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[extras]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["DataFrames", "Test"]
