[deps]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
PkgBenchmark = "32113eaa-f34f-5b0d-bd6c-c81e245fc73d"
SpringRank = "be6e8a61-07d1-4c53-9ea3-a8f885d7be3a"
